name: mdms_iosand
description: Distribution Management Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

  ## -- STATE MANAGEMENT
  get: ^4.6.5
  shared_preferences: ^2.1.0
  card_settings: ^3.3.0

  ## Network
  http: ^1.1.0
  fluttertoast: ^8.2.1
  unique_identifier: ^0.3.0

  ## -- Dashboard
  pie_chart: ^5.3.2

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.1.1

  ##flutter_facebook_auth: ^5.0.7
  ##google_sign_in: ^5.4.2

  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.2.16
  unique_list: ^1.0.1
  geolocator: ^10.1.0
  json_annotation: ^4.8.1
  date_format: ^2.0.7
  pdf: ^3.10.1
  flutter_pdfview: ^1.3.1
  share_extend: ^2.0.0
  printing: ^5.10.4
  permission_handler: ^11.0.1
  dio: ^5.1.2
  im_stepper: ^1.0.1+1
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  dropdown_button2: ^2.1.3
  google_maps_flutter: ^2.2.5
  grouped_list: ^5.1.2
  getwidget: ^4.0.0
  ##high_chart: ^2.0.3
  syncfusion_flutter_datagrid: ^23.2.4
  intl: ^0.18.1
  path_provider: ^2.1.1
  pattern_formatter: ^3.0.0
  liquid_pull_refresh: ^1.0.6
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  high_chart:
    path: G://Android//Project//high_chart

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/