// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnRKAywKfTOAMiYPSnsrInkEi7gvLR5s8',
    appId: '1:11059058424:android:4ac8d2baf03ce14a9ecd0d',
    messagingSenderId: '11059058424',
    projectId: 'mdmsiosand-4b89f',
    databaseURL:
        'https://mdmsiosand-4b89f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdmsiosand-4b89f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCROrpw6lnpx-n73d-BEMSOI3l0r22naPc',
    appId: '1:11059058424:ios:4567e58697f10e859ecd0d',
    messagingSenderId: '11059058424',
    projectId: 'mdmsiosand-4b89f',
    databaseURL:
        'https://mdmsiosand-4b89f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdmsiosand-4b89f.appspot.com',
    androidClientId:
        '11059058424-o79883jf4gmgcehep1oeef957vfavud7.apps.googleusercontent.com',
    iosClientId:
        '11059058424-6hqubmrg3qf6e0j5ukhgjbdaiu9j978n.apps.googleusercontent.com',
    iosBundleId: 'com.smgroup.mdms.iosand.mdmsIosand',
  );
}
